/**
 * Canonical category per icon key.
 * Used to fix seed data + sync existing MongoDB documents.
 *
 * Categories:
 *   build, cloud, cms, database, design, devops, framework, game,
 *   hardware, ide, language, library, markup, ml, os, productivity,
 *   runtime, social, testing, tool
 */
const iconCategoryMap = {
  // —— build (bundlers, package managers, build systems) ——
  babel: 'build',
  cmake: 'build',
  gradle: 'build',
  gulp: 'build',
  maven: 'build',
  npm: 'build',
  pnpm: 'build',
  rollupjs: 'build',
  vite: 'build',
  webpack: 'build',
  yarn: 'build',

  // —— cloud ——
  appwrite: 'cloud',
  aws: 'cloud',
  azure: 'cloud',
  cloudflare: 'cloud',
  firebase: 'cloud',
  gcp: 'cloud',
  heroku: 'cloud',
  netlify: 'cloud',
  openshift: 'cloud',
  openstack: 'cloud',
  supabase: 'cloud',
  vercel: 'cloud',
  workers: 'cloud',

  // —— cms ——
  wordpress: 'cms',

  // —— database ——
  cassandra: 'database',
  dynamodb: 'database',
  elasticsearch: 'database',
  mongodb: 'database',
  mysql: 'database',
  planetscale: 'database',
  postgres: 'database',
  postgresql: 'database',
  redis: 'database',
  sqlite: 'database',

  // —— design (UI / creative / CAD / video / audio production) ——
  ableton: 'design',
  ae: 'design',
  ai: 'design',
  au: 'design',
  autocad: 'design',
  blender: 'design',
  figma: 'design',
  pr: 'design',
  ps: 'design',
  sketchup: 'design',
  webflow: 'design',
  xd: 'design',

  // —— devops (VCS, CI/CD, containers, infra, monitoring, messaging) ——
  ansible: 'devops',
  bitbucket: 'devops',
  docker: 'devops',
  git: 'devops',
  github: 'devops',
  githubactions: 'devops',
  gitlab: 'devops',
  grafana: 'devops',
  jenkins: 'devops',
  kafka: 'devops',
  kubernetes: 'devops',
  nginx: 'devops',
  prometheus: 'devops',
  rabbitmq: 'devops',
  sentry: 'devops',
  terraform: 'devops',

  // —— framework (app / UI / desktop frameworks & engines) ——
  actix: 'framework',
  adonis: 'framework',
  alpinejs: 'framework',
  angular: 'framework',
  astro: 'framework',
  bootstrap: 'framework',
  django: 'framework',
  electron: 'framework',
  elysia: 'framework',
  ember: 'framework',
  express: 'framework',
  fastapi: 'framework',
  flask: 'framework',
  flutter: 'framework',
  gatsby: 'framework',
  gtk: 'framework',
  ktor: 'framework',
  laravel: 'framework',
  nestjs: 'framework',
  nextjs: 'framework',
  nuxtjs: 'framework',
  qt: 'framework',
  rails: 'framework',
  react: 'framework',
  remix: 'framework',
  rocket: 'framework',
  ros: 'framework',
  solidjs: 'framework',
  spring: 'framework',
  svelte: 'framework',
  symfony: 'framework',
  tailwind: 'framework',
  tauri: 'framework',
  vue: 'framework',
  windicss: 'framework',
  yew: 'framework',

  // —— game ——
  bevy: 'game',
  gamemakerstudio: 'game',
  godot: 'game',
  haxeflixel: 'game',
  robloxstudio: 'game',
  unity: 'game',
  unreal: 'game',

  // —— hardware ——
  arduino: 'hardware',
  raspberrypi: 'hardware',

  // —— ide ——
  androidstudio: 'ide',
  atom: 'ide',
  clion: 'ide',
  eclipse: 'ide',
  emacs: 'ide',
  idea: 'ide',
  neovim: 'ide',
  phpstorm: 'ide',
  pycharm: 'ide',
  replit: 'ide',
  rider: 'ide',
  sublime: 'ide',
  vim: 'ide',
  visualstudio: 'ide',
  vscode: 'ide',
  vscodium: 'ide',
  webstorm: 'ide',

  // —— language (programming / scripting languages) ——
  aiscript: 'language',
  bash: 'language',
  c: 'language',
  clojure: 'language',
  coffeescript: 'language',
  cpp: 'language',
  crystal: 'language',
  cs: 'language',
  dart: 'language',
  elixir: 'language',
  forth: 'language',
  fortran: 'language',
  gherkin: 'language',
  go: 'language',
  graphql: 'language',
  haskell: 'language',
  haxe: 'language',
  java: 'language',
  js: 'language',
  kotlin: 'language',
  lua: 'language',
  matlab: 'language',
  nim: 'language',
  ocaml: 'language',
  octave: 'language',
  perl: 'language',
  php: 'language',
  pkl: 'language',
  powershell: 'language',
  py: 'language',
  python: 'language',
  r: 'language',
  ruby: 'language',
  rust: 'language',
  scala: 'language',
  solidity: 'language',
  swift: 'language',
  ts: 'language',
  typescript: 'language',
  v: 'language',
  vala: 'language',
  zig: 'language',

  // —— library (libs, ORMs, state, UI kits, creative-coding libs) ——
  apollo: 'library',
  d3: 'library',
  discordjs: 'library',
  emotion: 'library',
  hibernate: 'library',
  htmx: 'library',
  jquery: 'library',
  lit: 'library',
  materialui: 'library',
  p5js: 'library',
  pinia: 'library',
  prisma: 'library',
  processing: 'library',
  reactivex: 'library',
  redux: 'library',
  sequelize: 'library',
  styledcomponents: 'library',
  threejs: 'library',
  vuetify: 'library',

  // —— markup (markup, stylesheets, templating, document formats) ——
  css: 'markup',
  html: 'markup',
  latex: 'markup',
  less: 'markup',
  md: 'markup',
  pug: 'markup',
  sass: 'markup',
  svg: 'markup',

  // —— ml ——
  opencv: 'ml',
  pytorch: 'ml',
  sklearn: 'ml',
  tensorflow: 'ml',

  // —— os ——
  apple: 'os',
  arch: 'os',
  bsd: 'os',
  debian: 'os',
  kali: 'os',
  linux: 'os',
  mint: 'os',
  nix: 'os',
  plan9: 'os',
  redhat: 'os',
  ubuntu: 'os',
  windows: 'os',

  // —— productivity (notes, email, docs) ——
  gmail: 'productivity',
  notion: 'productivity',
  obsidian: 'productivity',

  // —— runtime ——
  bun: 'runtime',
  deno: 'runtime',
  dotnet: 'runtime',
  nodejs: 'runtime',
  wasm: 'runtime',

  // —— social / community platforms ——
  bots: 'social',
  codepen: 'social',
  devto: 'social',
  discord: 'social',
  instagram: 'social',
  linkedin: 'social',
  mastodon: 'social',
  misskey: 'social',
  stackoverflow: 'social',
  twitter: 'social',

  // —— testing ——
  cypress: 'testing',
  jest: 'testing',
  selenium: 'testing',
  vitest: 'testing',

  // —— tool (misc protocols, platforms, utilities) ——
  activitypub: 'tool',
  anaconda: 'tool',
  azul: 'tool',
  fediverse: 'tool',
  ipfs: 'tool',
  postman: 'tool',
  regex: 'tool',
};

module.exports = iconCategoryMap;
